# The URL the site will be built for
base_url = "https://fprasx.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

title = "Felix Prasanna"
description = "MIT student who enjoys performance engineering, compilers, and creating unconventional code"
generate_feed = true
feed_filename = "atom.xml"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
hyde_theme = "theme-base-0d"
hyde_links = [
    {url = "/about", name = "About"},
    {url = "/notes", name = "Course Notes"},
    {url = "/articles", name = "Articles"},
    {url = "https://github.com/fprasx", name = "GitHub"},
    {url = "/atom.xml", name = "RSS"},
]
hyde_sticky = false
